Form/Type/SearchType.php
<?php

namespace Nitra\ProductBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class SearchType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('term', 'text', array(
            'required'      => false,
            'label'         => ' ',
            'attr'          => array(
                'class'         => 'nitra_search_suggest',
            ),
        ));
        $builder->add('search', 'button', array(
            'label'         => 'search.button',
            'attr'          => array(
                'class'         => 'js-click-on-search',
            ),
        ));
    }
    
    public function getName()
    {
        return 'nitra_search';
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'translation_domain' => 'NitraProductBundle',
        ));
    }
}

Resources/views/breadcrumbs.html.twig
{% trans_default_domain "NitraProductBundle" %}

{% block breadcrumbs %}
    <div class="breadcrumbs">
        {% block breadcrumbs_content %}
            {% block breadscrumb_first_item %}
                <a class="first" href="{{ path("nitra_store_home_index") }}">{{ 'breadscrumbs.home'|trans }}</a>
            {% endblock breadscrumb_first_item %}

            {% for item in breadscrumbs %}
                {% block breadscrumb_item %}
                    {% block breadscrumb_separator %}
                        <span class="separator">{{ 'breadscrumbs.separator'|trans }}</span>
                    {% endblock breadscrumb_separator %}

                    {% if loop.last %}
                        {% block breadscrumb_last_item %}
                            <span class="last">{{ item.name|trans }}</span>
                        {% endblock breadscrumb_last_item %}
                    {% else %}
                        {% block breadscrumb_link %}
                            <a href="{{ path(item.route, item.routeParameters) }}">{{ item.name|trans }}</a>
                        {% endblock breadscrumb_link %}
                    {% endif %}
                {% endblock breadscrumb_item %}
            {% endfor %}
        {% endblock breadcrumbs_content %}
    </div>
{% endblock breadcrumbs %}